# Generated by Django 3.0.2 on 2020-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='default.jpg', upload_to='user/profile_pic'),
        ),
    ]
